version: "3" # optional since v1.27.0
services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  db:
    image: postgres:13
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=change-in-production
      - POSTGRES_DB=moodle_bot
  
  backend:
    shm_size: '8gb'
    command: "yarn start"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
     - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - 3000:3000
volumes:
  db_vol: null
  redis_data: