export const ASSIGNMENT_QUEUES = {
  SHOW_ASSIGNMENTS: 'show-assignments',
};

const MILLISECONDS_IN_SECOND = 1000;
const SECONDS_IN_MINUTE = 60;

export const ASSIGNMENT_REQUEST_COOLDOWN_MILLISECONDS = 5 * SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND; // 5 minutes
export const ASSIGNMENT_NOTIFICATION_COOLDOWN_MILLISECONDS = 5 * SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND; // 5 minutes
